spring:
  datasource:
    url: jdbc:sqlserver://employee-database.database.windows.net:1433;database=Employee;user=employeedb@employee-database;password=ABCD789k;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080
